
bookdetails_service_url: http://localhost:8081

## DOCU: https://resilience4j.readme.io/docs/getting-started-3
resilience4j:
  circuitbreaker:
    instances:
      outbound-service:
        registerHealthIndicator: true                               # Register actuator endpoint for circuit-breaker health of target app
        minimumNumberOfCalls: 10                                    # Min calls to evaluate the min threshold
        failureRateThreshold: 50                                    # Failure threshold in percentage
        waitDurationInOpenState: 5s                                 # Time after which CB should transition from open to half-open state
        automaticTransitionFromOpenToHalfOpenEnabled: true          # This will ensure CB automatically transition from open to half open state
        permittedNumberOfCallsInHalfOpenState: 3                    # This will ensure only limited calls are allowed in half open state
        slidingWindowType: COUNT_BASED                              # This is the type used to record the outcome of calls when the CB is closed
        slidingWindowSize: 10                                       # This is the size used to record the outcome of calls when the CB is closed.
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException # target service is producing 5XX
          - org.springframework.web.client.ResourceAccessException  # target service is down and resource is not accessible

  retry:
    instances:
      outbound-service:
        max-attempts: 3                                             # How many attempts to make in case of exceptions
        wait-duration: 1s                                           # Time between each retry attempt
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException # target service is producing 5XX
          - org.springframework.web.client.ResourceAccessException  # target service is down and resource is not accessible

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---

spring:
  config:
    activate:
      on-profile: test

bookdetails_service_url: http://localhost:8081